In [11]:
import pandas as pd

In [12]:
reviews = pd.read_parquet('D:/escritorio/STEAM/parquet/reviews.parquet')
output = pd.read_parquet('D:/escritorio/STEAM/parquet/output_game.parquet')
items = pd.read_parquet('D:/escritorio/STEAM/parquet/item.parquet')

Preparamos los datos

In [13]:
output.rename(columns={'id': 'item_id'}, inplace=True)
output

,genres,app_name,price,item_id,developer,release_year
88310,Action,Lost Summoner Kitty,4.99,761140,Kotoshiro,2018
88311,Free to Play,Ironbound,0.00,643980,Secret Level SRL,2018
88312,Casual,Real Pool 3D - Poolians,0.00,670290,Poolians.com,2017
88313,Action,弹炸人2222,0.99,767400,彼岸领域,2017
88315,Action,Battle Royale Trainer,3.99,772540,Trickjump Games Ltd,2018
...,...,...,...,...,...,...
108822,Indie,Fantasy Grounds - Mini-Dungeon #012: Nekh-ta-N...,2.99,552860,"SmiteWorks USA, LLC",2016
108823,Indie,Fantasy Grounds - Kingdoms (5E),14.99,557300,"SmiteWorks USA, LLC",2016
108824,Indie,Fantasy Grounds - Mini-Dungeon #013: The Case ...,2.99,553360,"SmiteWorks USA, LLC",2016
108825,Adventure,A New Beginning - Final Cut Soundtrack,2.99,558220,Daedalic Entertainment,2016
108826,Adventure,Memoria Soundtrack,2.99,558210,Daedalic Entertainment,2016

Unimos los 3 dataframes

In [14]:
# Unir 'itemseda' y 'outputeda' usando 'item_id' como clave
merged_df = pd.merge(items, output, on='item_id', how='inner')

# Unir 'merged_df' y 'reviewseda' usando 'item_id' como clave
juntos = pd.merge(merged_df, reviews, on='item_id', how='inner')

# Mostrar el nuevo DataFrame
juntos

,item_id,item_name,playtime_forever,items_count,user_id_x,genres,app_name,price,developer,release_year,posted_year,user_id_y,recommend,review,sentiment_analysis
0,70,Half-Life,0,109,Nikiad,Action,Half-Life,9.99,Valve,1998,2015,EizanAratoFujimaki,True,ADVERTENCIA:Este Análisis contiene posibles Sp...,2
1,70,Half-Life,0,109,Nikiad,Action,Half-Life,9.99,Valve,1998,2011,GamerFag,True,If you own any half life but not this one that...,0
2,70,Half-Life,0,109,Nikiad,Action,Half-Life,9.99,Valve,1998,2014,76561198020928326,True,this game has had me hooked for over 4 years a...,2
3,70,Half-Life,0,109,Nikiad,Action,Half-Life,9.99,Valve,1998,2013,Bluegills,True,"This is, by far my most favourite game I have ...",2
4,70,Half-Life,0,109,Nikiad,Action,Half-Life,9.99,Valve,1998,2013,76561198071955492,True,Wow. This game was incredible. Half-Life is a ...,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3263254,305920,Another Perspective,30,704,Resplendentbadger,Adventure,Another Perspective,5.99,ShaunJS,2014,2015,laislabonita75,False,i really didn't like it. i'm sorry. slow and b...,0
3263255,235360,Prime World: Defenders,0,704,Resplendentbadger,Casual,Prime World: Defenders,9.99,Nival,2013,2013,76561198032373589,True,incredible,1
3263256,235360,Prime World: Defenders,0,704,Resplendentbadger,Casual,Prime World: Defenders,9.99,Nival,2013,2013,76561198014210785,True,"Tower Defense awesomeness (\/) (-,,-) (\/)",2
3263257,235360,Prime World: Defenders,217,122,darkus0haos,Casual,Prime World: Defenders,9.99,Nival,2013,2013,76561198032373589,True,incredible,1
3263258,235360,Prime World: Defenders,217,122,darkus0haos,Casual,Prime World: Defenders,9.99,Nival,2013,2013,76561198014210785,True,"Tower Defense awesomeness (\/) (-,,-) (\/)",2

Eliminamos columnas que no vamos a necesitar

In [15]:
# Especifica las columnas que deseas eliminar
columnas_a_eliminar = ['user_id_x', 'user_id_y','item_name', 'posted_year', 'review']
# Elimina las columnas no deseadas del DataFrame final
juntos = juntos.drop(columnas_a_eliminar, axis=1)
# Mostrar el nuevo DataFrame sin las columnas eliminadas
juntos

,item_id,playtime_forever,items_count,genres,app_name,price,developer,release_year,recommend,sentiment_analysis
0,70,0,109,Action,Half-Life,9.99,Valve,1998,True,2
1,70,0,109,Action,Half-Life,9.99,Valve,1998,True,0
2,70,0,109,Action,Half-Life,9.99,Valve,1998,True,2
3,70,0,109,Action,Half-Life,9.99,Valve,1998,True,2
4,70,0,109,Action,Half-Life,9.99,Valve,1998,True,2
...,...,...,...,...,...,...,...,...,...,...
3263254,305920,30,704,Adventure,Another Perspective,5.99,ShaunJS,2014,False,0
3263255,235360,0,704,Casual,Prime World: Defenders,9.99,Nival,2013,True,1
3263256,235360,0,704,Casual,Prime World: Defenders,9.99,Nival,2013,True,2
3263257,235360,217,122,Casual,Prime World: Defenders,9.99,Nival,2013,True,1
3263258,235360,217,122,Casual,Prime World: Defenders,9.99,Nival,2013,True,2

Consultamos si tenemos valores nullos o lugares vacios

In [16]:
print(juntos.isnull().sum())

item_id               0
playtime_forever      0
items_count           0
genres                0
app_name              0
price                 0
developer             0
release_year          0
recommend             0
sentiment_analysis    0
dtype: int64

Eliminamos los valores duplicados

In [17]:
# Elimina las filas duplicadas del DataFrame
unidos = juntos.drop_duplicates()
# Mostrar el DataFrame sin valores duplicados
unidos

,item_id,playtime_forever,items_count,genres,app_name,price,developer,release_year,recommend,sentiment_analysis
0,70,0,109,Action,Half-Life,9.99,Valve,1998,True,2
1,70,0,109,Action,Half-Life,9.99,Valve,1998,True,0
7,70,0,109,Action,Half-Life,9.99,Valve,1998,True,1
56,70,139,48,Action,Half-Life,9.99,Valve,1998,True,2
57,70,139,48,Action,Half-Life,9.99,Valve,1998,True,0
...,...,...,...,...,...,...,...,...,...,...
3263254,305920,30,704,Adventure,Another Perspective,5.99,ShaunJS,2014,False,0
3263255,235360,0,704,Casual,Prime World: Defenders,9.99,Nival,2013,True,1
3263256,235360,0,704,Casual,Prime World: Defenders,9.99,Nival,2013,True,2
3263257,235360,217,122,Casual,Prime World: Defenders,9.99,Nival,2013,True,1
3263258,235360,217,122,Casual,Prime World: Defenders,9.99,Nival,2013,True,2

In [18]:
print(unidos.isin(['', ' ', None]).any().any())

False

Procedemos a guardar en formato parquet

In [19]:
unidos.to_parquet('D:/escritorio/STEAM/parquet/engineer.parquet')